version: "3"

services:
    php84:
        build:
            context: .docker/php/8.4
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./:/var/www
volumes:
    aviso:
