name: CI

on:
    push:
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    extensions: mailparse, mbstring
                    coverage: none

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-interaction

            -   name: PHPUnit
                run: vendor/bin/phpunit

            -   name: PHPStan
                run: vendor/bin/phpstan analyse --no-progress

            -   name: PHP CodeSniffer
                run: vendor/bin/phpcs

            -   name: Security audit
                run: composer audit
